config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :comments
  end

  root "posts#index"

  get '/about', to: 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy		
		@comment = Comment.find(params[:post_id])
		@comment.destroy
		
		@post = Post.find(params[:id])
		
		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:destroy, :show, :edit, :update]

	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show

	end

	def destroy
		@post.destroy
			redirect_to posts_path
	end

	def edit
		
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	private

		def find_post
			@post = Post.find(params[:id])
		end

		def post_params
			params.require(:post).permit(:title, :body)	
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_title"><%= time_ago_in_words(comment.created_at) %> ago | 
			<%= link_to "Delete", post_comment_path(comment), method: :delete,data: { confirm: "Are you sure?"} %> </p>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<br>
	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>tumblr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Raleway' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico.png' %>
  </head> 

  <body>
	  <div id ="sidebar">
	  	<ul>
	  		<li class="category"><%=link_to "tumblr", root_path %></li>
	  		<li><%= link_to "Posts", root_path%></li>
	  		<li><%= link_to "About", about_path%></li>
	  	</ul>
	  	<% unless user_signed_in? %>
	  		<p class="sign_in"><%= link_to "User Login", new_user_session_path %></p>
	  	<% end %>	
	  </div>

	  <div id="main_content">
	  		<div id="header">
	  		<% if current_page?(root_path || posts_path) %>
	  			<p style="margin-left: -37px;">Post Feed</p>
	  		<% elsif current_page?(about_path) %>	
	  			<p style="margin-left: -37px;">About me</p>
	  		<% else %>
	  			<p style="margin-left: -37px;"><%= link_to "< Back to Post Feed", root_path %></p>
	  		<% end %>

	  		<%if user_signed_in? %>
	  			<div class="buttons">
		  			<button class="button"><%=link_to "Make Post", new_post_path %></button>
		  			<button class="button"><%=link_to "Sign Out", destroy_user_session_path, method: :delete %></button>
	  			</div>
	  		<% end %>
	  		</div>
	  		<div style="color:#f97070">
		  		<p class="notice"><%= notice %></p>
	      		<p class="alert"><%= alert %></p>
	      	</div>
	  	<%= yield %>
	  </div>


	  
   
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.jpeg" %>
	</div>

	<div id="content">
		<h1>It's Mr. Stick Figure</h1>
		<p>Stick Figure is an American reggae and dub band based in Southern California. The group has released six full-length albums, all of which were written and produced by frontman Scott Woodruff, a singer-songwriter who until 2009 was based in Massachusetts. In 2012 Woodruff released the fifth Stick Figure album, Burial Ground, to critical acclaim. The album reached no. 1 on the iTunes and Billboard Reggae charts. The band began touring with a new line up after the release of Burial Ground, and has since toured throughout the United States with reggae groups such as Rebelution, Slightly Stoopid, The Green, Passafire, Tribal Seeds and The Expendables. Cocoa, an Australian Shepherd, typically joins the band on stage. The group's sixth album, Set in Stone, was released in November 2015 and reached No. 1 on the Billboard Reggae Albums Chart, also reaching No. 101 on the Billboard 200 and No. 1 on Heatseekers Albums chart.</p>
	</div>
</div>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1 id="content">Edit Post</h1>

	<%= form_for :post, url: post_path, method: :put do |f| %>
		<div id="content">
			<% if @post.errors.any? %>
			  <div id="errors">
			  	<h2><%=pluralize(@post.errors.count, "error") %> stopped this from saving</h2>
			  	<ul>
			  		<% @post.errors.full_messages.each do |msg| %>
			  			<li><%= msg %></li>
			  		<% end %>
			  	</ul>
			  </div>
			<% end %>
 
		  <p>
		  	<%= f.label :title %><br/>
		  	<%= f.text_field :title %>
		  </p>

		  <p>
		  	<%= f.label :body %><br/>
		  	<%= f.text_area :body%>
		  </p>
		 
		  <%= f.submit %>
		</div>  
	<% end %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%=link_to post.title, post %></h2>
		<p class="body"><%= truncate(post.body, length:100)%>
		<p class="body"><%= time_ago_in_words(post.created_at) %> ago</p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1 id="content">Make something</h1>

	<%= form_for :post, url: posts_path do |f| %>
	<div id="content">
	<% if @post.errors.any? %>
	  <div id="erroes">
	  	<h2><%=pluralize(@post.errors.count, "error") %> stopped this from saving</h2>
	  	<ul>
	  		<% @post.errors.full_messages.each do |msg| %>
	  			<li><%= msg %></li>
	  		<% end %>
	  	</ul>
	  </div>
	<% end %>

	  <p>
	  	<%= f.label :title %><br/>
	  	<%= f.text_field :title %>
	  </p>

	  <p>
	  	<%= f.label :body %><br/>
	  	<%= f.text_area :body %>
	  </p>
	 
	  <%= f.submit %>
	</div>  
	<% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>


	<p class="date_and_author">
		Submitted <%= time_ago_in_words(@post.created_at) %> ago 			
			<% @current = current_user %>
			
				<% if  @current != nil && @post.user_id == @current.id %>
					<%= link_to "| Update |", edit_post_path(@post)%>
					<%= link_to " Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"}%>
				<% end %>


		</p>
	
	<%= simple_format(@post.body, class: 'body')  %>

	<div id="comments">
		<h3><%= pluralize(@post.comments.count, "Comment") %></h3>
		<%= render @post.comments %>
		<h4>Join discussion</h4>
		<%= render "comments/form" %>
	</div>
		
</div>